name: background_fetch
description: Periodic callbacks in the background for both iOS and Android.  Includes Android Headless implementation.
version: 1.2.1
homepage: https://github.com/transistorsoft/flutter_background_fetch

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"
dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: BackgroundFetchPlugin

